DELETE http://localhost:3001/api/persons/63fe531cebb33fed86f6bf83

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Anonymous",
    "number": "51029831029"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "51029831029"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Anonymous"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Arto hellas",
    "number": "51029831029"
}

###

GET http://localhost:3001/api/1
